export const tagLabels = {
  backbone: "Backbone.js",
  fastify: "Fastify / Node",
  gatsby: "Gatsby / React",
  gcp: "GCP",
  graphql: "GraphQL",
  javascript: "JavaScript",
  mongo: "MongoDB",
  net: ".NET",
  node: "Node",
  postgres: "PostgreSQL",
  prosemirror: "ProseMirror",
  rpi: "Raspberry Pi",
  svelte: "Svelte.js",
  typescript: "TypeScript",
  unity3d: "Unity 3D",
  wasm: "WebAssembly",
  wordpress: "WordPress",
};
