export const tagLabels: Record<string, string> = {
  backbonedotjs: "Backbone.js",
  graphql: "GraphQL",
  javascript: "JavaScript",
  mongodb: "MongoDB",
  dotnet: ".NET / C#",
  nestjs: "NestJS",
  nextdotjs: "Next.js",
  nodedotjs: "Node.js",
  postgresql: "PostgreSQL",
  prosemirror: "ProseMirror",
  raspberrypi: "Raspberry Pi",
  rubyonrails: "Ruby on Rails",
  tensorflow: "TensorFlow",
  typescript: "TypeScript",
  unity: "Unity 3D",
  vuedotjs: "Vue.js",
  webassembly: "WebAssembly",
  wordpress: "WordPress",
  nuxtdotjs: "NuxtJS / Vue",
  mysql: "MySQL",
  react: "React",
  redux: "Redux",
  gatsby: "Gatsby",
  svelte: "Svelte",
  django: "Django",
  express: "Express",
  flask: "Flask",
  fastify: "Fastify",
  acf: "ACF",
  algolia: "Algolia",
  apollo: "Apollo",
  aws: "AWS",
  azure: "Azure",
  bootstrap: "Bootstrap",
  bulma: "Bulma",
  cypress: "Cypress",
  d3: "D3",
  datadog: "Datadog",
  docker: "Docker",
  drupal: "Drupal",
  electron: "Electron",
  elasticsearch: "Elasticsearch",
  firebase: "Firebase",
  git: "Git",
  github: "GitHub",
  googlecloud: "Google Cloud",
  grommet: "Grommet",
  heroku: "Heroku",
  sass: "Sass",
  typo3: "TYPO3",
  mariadb: "MariaDB",
  vite: "Vite",
  elementor: "Elementor",
  laravel: "Laravel",
  php: "PHP",
  python: "Python",
  ruby: "Ruby",
  rust: "Rust",
  symfony: "Symfony",
  vue: "Vue",
  webpack: "Webpack",
  scss: "SCSS",
  sql: "SQL",
  html5: "HTML",
  css3: "CSS",
  jquery: "jQuery",
  microsoftexcel: "Excel",
  visualstudiocode: "VS code",
  dotenv: ".ENV",
};

export const tagAncestors: Record<string, string[]> = {
  backbonedotjs: ["javascript"],
  cypress: ["javascript"],
  django: ["python"],
  express: ["nodedotjs", "javascript"],
  fastify: ["nodedotjs", "javascript"],
  flask: ["python"],
  gatsby: ["react", "javascript"],
  nestjs: ["nodedotjs", "javascript"],
  nextdotjs: ["react", "javascript"],
  nodedotjs: ["javascript"],
  react: ["javascript"],
  redux: ["javascript"],
  svelte: ["javascript"],
  typescript: ["javascript"],
  vuedotjs: ["javascript"],
  wordpress: ["php"],
  acf: ["wordpress"],
  docker: ["javascript"],
  drupal: ["php"],
  vite: ["javascript"],
  elementor: ["wordpress"],
  laravel: ["php"],
  sass: ["css3"],
};
