export const tagLabels: Record<string, string> = {
  backbonedotjs: "Backbone",
  graphql: "GraphQL",
  javascript: "JavaScript",
  mongodb: "MongoDB",
  dotnet: ".NET / C#",
  nestjs: "NestJS",
  nextdotjs: "Next.js",
  nodedotjs: "Node",
  postgresql: "Postgres",
  prosemirror: "ProseMirror",
  pwa: "PWA",
  raspberrypi: "Raspberry Pi",
  rubyonrails: "Rails",
  tensorflow: "TensorFlow",
  typescript: "TypeScript",
  unity: "Unity 3D",
  vuedotjs: "Vue",
  webassembly: "Wasm",
  wordpress: "WordPress",
};
