{
  env: {
    browser: true,
    es6: true,
    node: true
  },
  extends: ["eslint:recommended", 'plugin:@typescript-eslint/recommended'],
  ignorePatterns: ['*.cjs'],
  overrides: [{
    files: ['*.svelte'],
    processor: 'svelte3/svelte3'
  }],
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaVersion: 2019,
    requireConfigFile: false,
    sourceType: 'module'
  },
  plugins: ['svelte3', '@typescript-eslint'],
  rules: {
    "@typescript-eslint/no-inferrable-types": 0,
    "@typescript-eslint/no-unused-vars": [1, {
      argsIgnorePattern: "^_"
    }],
    "brace-style": [1, "1tbs"],
    "camelcase": 1,
    "comma-dangle": [1, "always-multiline"],
    "curly": [1, "multi-line"],
    "eol-last": 1,
    "eqeqeq": [2, "always", {
      "null": "ignore"
    }],
    "no-console": [1, {
      allow: ["warn", "error"]
    }],
    "no-constant-condition": 2,
    "no-implicit-coercion": 2,
    "no-param-reassign": 1,
    "no-trailing-spaces": [1, { "skipBlankLines": true }],
    "no-unused-vars": 1,
    "no-var": 2,
    "prefer-const": 1,
    "quote-props": [1, "consistent"],
    "quotes": [1, "double"],
    "semi": 1,
  },
  settings: {
    'svelte3/typescript': true
  }
}
